SUGGEST_BUTTON = "\u2709\ufe0f Предложить контент"
PROFILE_BUTTON = "\U0001F464 Профиль"
TOURNAMENTS_BUTTON = "\U0001F3C6 Турниры"
BACK_BUTTON = "\u2B05\ufe0f Назад"
JOIN_BUTTON = "Участвовать"
RATING_BUTTON = "Рейтинг игроков"
FEEDBACK_BUTTON = "\U0001F4AC Обратная связь"
PROPOSAL_BUTTON = "Предложения"
QUESTION_BUTTON = "Вопрос"
COMPLAINT_BUTTON = "Жалоба"

CREATE_TOURNAMENT_BUTTON = "Создать турнир"
MUTED_LIST_BUTTON = "Список мута"
BANNED_LIST_BUTTON = "Список забаненных"
ASSIGN_ROLE_BUTTON = "Назначить админа/модератора"
MANAGE_TOURNAMENTS_BUTTON = "Управление турнирами"
